// Generated by CoffeeScript 1.7.1
(function() {
  var User;

  User = (function() {
    function User() {}

    User.prototype.toDomainModel = function(user) {
      this.id = user.id;
      this.name = user.name;
      return this.sex = user.sex;
    };

    return User;

  })();

}).call(this);

//# sourceMappingURL=user.map
