// Generated by CoffeeScript 1.7.1
(function () {
    exports.mysql = {
        database: "test",
        protocol: "mysql",
        host: "127.0.0.1",
        port: 3306,
        username: "root",
        password: "",
        query: {
            pool: true,
            debug: true
        }
    };

}).call(this);

//# sourceMappingURL=config.map
