// Generated by CoffeeScript 1.7.1
(function() {
  exports.mysql = {
    database: "test",
    protocol: "mysql",
    host: "112.124.100.167",
    port: 3306,
    username: "root",
    password: "123456",
    query: {
      pool: true,
      debug: true
    }
  };

}).call(this);

//# sourceMappingURL=config.map
