// Generated by CoffeeScript 1.7.1
(function() {
  var Repository;

  Repository = (function() {
    function Repository() {}

    Repository.prototype.construct = function(modelDef) {
      return this.modelDef = modelDef;
    };

    Repository.prototype.add = Repository.modelDef;

    return Repository;

  })();

}).call(this);

//# sourceMappingURL=repository.map
