// Generated by CoffeeScript 1.7.1
(function() {
  var Repository;

  Repository = (function() {
    function Repository(modelDef) {
      this.modelDef = modelDef;
    }

    Repository.prototype.find = function(conditions, limit, order, callback) {
      if (order == null) {
        order = {};
      }
      if (limit) {
        return this.modelDef.find(conditions, order, limit, function(err, models) {
          if (err) {
            callback(err);
          }
          return callback(err, models);
        });
      } else {
        return this.modelDef.find(conditions, order, function(err, models) {
          if (err) {
            callback(err);
          }
          return callback(err, models);
        });
      }
    };

    Repository.prototype.findFirstOrDefault = function(conditions, order, callback) {
      if (order == null) {
        order = {};
      }
      return this.modelDef.find(conditions, order, 1, function(err, model) {
        if (err) {
          callback(err);
        }
        return callback(err, model);
      });
    };

    Repository.prototype.findByPaged = function(conditions, order, pageNo, pageSize, callback) {
      if (order == null) {
        order = {};
      }
      return this.modelDef.find(conditions, order).offset((pageNo - 1) * pageSize).limit(pageSize).run((function(_this) {
        return function(err, models) {
          if (err) {
            callback(err);
          }
          return _this.modelDef.count(conditions, function(err, count) {
            var pagedModel;
            if (err) {
              callback(err);
            }
            pagedModel = {
              pageNo: pageNo,
              pageSize: pageSize,
              totalCount: count,
              data: models
            };
            return callback(err, pagedModel);
          });
        };
      })(this));
    };

    Repository.prototype.count = function(conditions, callback) {
      return this.modelDef.count(conditions, function(err, count) {
        if (err) {
          callback(err);
        }
        return callback(err, count);
      });
    };

    Repository.prototype.exists = function(conditions, callback) {
      return this.modelDef.exists(conditions, function(err, exists) {
        if (err) {
          callback(err);
        }
        return callback(err, exists);
      });
    };

    Repository.prototype.remove = function(primaryKey, callback) {
      return this.modelDef.get(primaryKey, function(err, model) {
        if (err) {
          callback(err);
        }
        return model.remove(function(err) {
          if (err) {
            callback(err);
          }
          return callback(err, true);
        });
      });
    };

    Repository.prototype.update = function(primaryKey, conditions, callback) {
      return this.modelDef.get(primaryKey, function(err, model) {
        if (err) {
          callback(err);
        }
        return model.save(conditions, function(err) {
          if (err) {
            callback(err);
          }
          return callback(err, true);
        });
      });
    };

    Repository.prototype.add = function(items, callback) {
      return this.modelDef.create(items, function(err, items) {
        if (err) {
          callback(err);
        }
        return callback(err, items);
      });
    };

    return Repository;

  })();

  module.exports = Repository;

}).call(this);

//# sourceMappingURL=repository.map
