// Generated by CoffeeScript 1.7.1
(function () {
    var createUer, createUerImp, createUerImpCallBack, userRepo;

    userRepo = require('../domain/domain.repository/userRepo');

    createUer = function (req, res) {
        var model, serviceReq;
        serviceReq = {
            id: req.body.id,
            name: req.body.name,
            sex: req.body.sex
        };
        model = req.model.user;
        return createUerImp(serviceReq, model, res, createUerImpCallBack);
    };

    createUerImp = function (serviceReq, model, res, cb) {
        return userRepo.create(serviceReq, model, function (err, serviceRes) {
            return cb(err, res, serviceRes);
        });
    };

    createUerImpCallBack = function (err, res, serviceRes) {
        return res.send(Json.stringify(serviceRes));
    };

    exports.create = createUer;

}).call(this);

//# sourceMappingURL=user.map
