// Generated by CoffeeScript 1.7.1
(function() {
  var UserRepository, createUer;

  UserRepository = require('../domain/domain.repository/userRepo');

  createUer = function(req, res) {
    var model, serviceReq, userRepo;
    serviceReq = {
      id: req.query.id,
      name: req.query.name,
      sex: req.query.sex
    };
    model = req.models.user;
    userRepo = new UserRepository(model);
    return userRepo.add([serviceReq], function(err, items) {
      var serviceRes;
      if (err) {
        res.send(err);
      }
      serviceRes = items;
      return res.send(Json.stringify(serviceRes));
    });
  };

  exports.create = createUer;

}).call(this);

//# sourceMappingURL=user.map
