// Generated by CoffeeScript 1.7.1
(function() {
  var userRepo;

  userRepo = (function() {
    function userRepo() {}

    userRepo.prototype.create = function(user, cb) {
      return user.create;
    };

    return userRepo;

  })();

}).call(this);

//# sourceMappingURL=userRepo.map
