// Generated by CoffeeScript 1.7.1
(function () {
    var orm, userDef;

    orm = require('orm');

    userDef = {
        tableName: "user",
        schema: {
            id: Number,
            name: String,
            sex: Number
        }
    };

    module.exports = function (db, cb, next) {
        return db.define(userDef.tableName, userDef.schema, next);
    };

    exports.create = function (user, cb) {
        return user.add;
    };

}).call(this);

//# sourceMappingURL=user.map
