// Generated by CoffeeScript 1.7.1
(function () {
    var orm, userDef;

    orm = require('orm');

    userDef = {
        tableName: "user",
        schema: {
            id: Number,
            name: String,
            sex: Number
        }
    };

    module.exports = function (db, cb) {
        var user;
        user = db.define(userDef.tableName, userDef.schema);
        return cb();
    };

}).call(this);

//# sourceMappingURL=user.map
